# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'compare.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTableWidget, QTableWidgetItem,
    QTreeWidget, QTreeWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(985, 899)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.dicomView = QGraphicsView(self.centralwidget)
        self.dicomView.setObjectName(u"dicomView")
        self.dicomView.setGeometry(QRect(30, 60, 361, 321))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 40, 61, 16))
        self.dicomTags_lable = QLabel(self.centralwidget)
        self.dicomTags_lable.setObjectName(u"dicomTags_lable")
        self.dicomTags_lable.setGeometry(QRect(650, 40, 61, 16))
        self.fileSelect = QPushButton(self.centralwidget)
        self.fileSelect.setObjectName(u"fileSelect")
        self.fileSelect.setEnabled(True)
        self.fileSelect.setGeometry(QRect(30, 10, 91, 23))
        self.fileSelect.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(400, 40, 61, 16))
        self.file_Forgery_Position_text = QLabel(self.centralwidget)
        self.file_Forgery_Position_text.setObjectName(u"file_Forgery_Position_text")
        self.file_Forgery_Position_text.setGeometry(QRect(140, 10, 261, 16))
        self.treeWidget = QTreeWidget(self.centralwidget)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(400, 60, 231, 321))
        self.treeWidget.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(640, 60, 241, 321))
        font = QFont()
        font.setPointSize(7)
        self.tableWidget.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(400, 490, 61, 16))
        self.tableWidget_2 = QTableWidget(self.centralwidget)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(640, 510, 241, 321))
        self.tableWidget_2.setFont(font)
        self.dicomTags_lable_2 = QLabel(self.centralwidget)
        self.dicomTags_lable_2.setObjectName(u"dicomTags_lable_2")
        self.dicomTags_lable_2.setGeometry(QRect(650, 490, 61, 16))
        self.dicomView_2 = QGraphicsView(self.centralwidget)
        self.dicomView_2.setObjectName(u"dicomView_2")
        self.dicomView_2.setGeometry(QRect(30, 510, 361, 321))
        self.treeWidget_2 = QTreeWidget(self.centralwidget)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidget_2.setHeaderItem(__qtreewidgetitem1)
        self.treeWidget_2.setObjectName(u"treeWidget_2")
        self.treeWidget_2.setGeometry(QRect(400, 510, 231, 321))
        self.treeWidget_2.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.file_isForgery_label_2 = QLabel(self.centralwidget)
        self.file_isForgery_label_2.setObjectName(u"file_isForgery_label_2")
        self.file_isForgery_label_2.setGeometry(QRect(30, 400, 111, 16))
        self.file_Forgery_Position_label_2 = QLabel(self.centralwidget)
        self.file_Forgery_Position_label_2.setObjectName(u"file_Forgery_Position_label_2")
        self.file_Forgery_Position_label_2.setGeometry(QRect(30, 430, 111, 16))
        self.fileSelect_2 = QPushButton(self.centralwidget)
        self.fileSelect_2.setObjectName(u"fileSelect_2")
        self.fileSelect_2.setEnabled(True)
        self.fileSelect_2.setGeometry(QRect(30, 460, 91, 23))
        self.fileSelect_2.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 490, 61, 16))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 400, 251, 16))
        self.label.setStyleSheet(u"background : rgb(217, 213, 200)")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 430, 251, 16))
        self.label_2.setStyleSheet(u"background : rgb(217, 213, 200)")
        self.file_isForgery_label_3 = QLabel(self.centralwidget)
        self.file_isForgery_label_3.setObjectName(u"file_isForgery_label_3")
        self.file_isForgery_label_3.setGeometry(QRect(450, 420, 111, 16))
        self.val1 = QLabel(self.centralwidget)
        self.val1.setObjectName(u"val1")
        self.val1.setGeometry(QRect(540, 400, 251, 16))
        self.val1.setStyleSheet(u"background : rgb(217, 213, 200)")
        self.val2 = QLabel(self.centralwidget)
        self.val2.setObjectName(u"val2")
        self.val2.setGeometry(QRect(540, 430, 251, 16))
        self.val2.setStyleSheet(u"background : rgb(217, 213, 200)")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 985, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Forensic Tool", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uc601\uc0c1 \ud654\uba74", None))
        self.dicomTags_lable.setText(QCoreApplication.translate("MainWindow", u"\ud0dc\uadf8 \uc815\ubcf4", None))
        self.fileSelect.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c1 \uc120\ud0dd", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc815\ubcf4", None))
        self.file_Forgery_Position_text.setText("")
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"2", None));
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc815\ubcf4", None))
        self.dicomTags_lable_2.setText(QCoreApplication.translate("MainWindow", u"\ud0dc\uadf8 \uc815\ubcf4", None))
        ___qtreewidgetitem1 = self.treeWidget_2.headerItem()
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("MainWindow", u"2", None));
        self.file_isForgery_label_2.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc704\ubcc0\uc870 \uc5ec\ubd80", None))
        self.file_Forgery_Position_label_2.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c \uc704\ubcc0\uc870 \uc704\uce58", None))
        self.fileSelect_2.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c2 \uc120\ud0dd", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc601\uc0c1 \ud654\uba74", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc758\uc2ec", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uba54\ud0c0\ub370\uc774\ud130(\uc0dd\uc131\uc2dc\uac04)", None))
        self.file_isForgery_label_3.setText(QCoreApplication.translate("MainWindow", u"\uac12 \ubd84\uc11d", None))
        self.val1.setText("")
        self.val2.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

